### ISSUE TITLE
Error Unexpected Token:

### ISSUE THREAD

**Issue by saikatharryc** [techpool/WBUT_api#1]
`cabox@box-codeanywhere:~/workspace$ node index.js                                                                                                          

/home/cabox/workspace/index.js:47  
                var req = http.request(options, (res) => {  
                                                       ^  
SyntaxError: Unexpected token >  
    at Module._compile (module.js:439:25)  
    at Object.Module._extensions..js (module.js:474:10)  
    at Module.load (module.js:356:32)  
    at Function.Module._load (module.js:312:12)  
    at Function.Module.runMain (module.js:497:10)  
    at startup (node.js:119:16)  
    at node.js:902:3        `

**Comment by techpool** [comment]
Which version of node? You need to update your node.js to the latest for ECMA6 support.

**Comment by saikatharryc** [comment]
its 10.25 stable..
i think this error for the website is down that's why.

**Comment by techpool** [comment]
Are you out? 
[https://nodejs.org/en/](url)

The official latest version is 6.3.0.
Did you make your own node?

**Comment by saikatharryc** [comment]
cabox@box-codeanywhere:~/workspace$ node -v  
v0.10.25  

this is old version sorry,, and now its updated, 
check it out ,,with the errors.. its now v6.3 
![image](https://cloud.githubusercontent.com/assets/15653282/17054869/1aaa93f2-5027-11e6-8696-1e10c07d4c73.png)
